name: Update key currency v2

on:
  workflow_dispatch:

jobs:
  phase1:
    name: Phase 1
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get install -y jq 
  phase2:
    name: Phase 2
    needs: phase1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        leagues: [Kalandra,Hardcore+Kalandra,Standard,Hardcore]
    steps:
    - name: Fetch currency data from ninja and create a json file for each league
      run: |
        curl "https://poe.ninja/api/data/CurrencyOverview?league=${{ matrix.leagues }}&type=Currency&language=ko" | jq '[.lines[] | select( .detailsId == "divine-orb" or .detailsId == "exalted-orb" ) | { id:.detailsId, chaosEquivalent:.chaosEquivalent, _t:.pay.sample_time_utc }]' > key-curr_${{ matrix.leagues }}.json
  phase3:
    name: Phase 3
    needs: phase2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_KEY }}
    - name: Commit and push
      run: |
        git config --global user.email "znoine+githubaction@gmail.com"
        git config --global user.name "znoine_githubaction"
        git add .
        git commit -m "action: Update key currency info"
        git push
